### ISSUE TITLE
Add toggle to produce compressed snapshots

### ISSUE THREAD

**Issue by dafty** [faustbrian/ARK-Snapshooter#6]
Snapshots can be compressed from 500mb to 150mb with gzip.

Maybe add a toggle so that we can produce gzipped snapshots. It will be faster for a client to download & decompress file, vs downloading an uncompressed file.

**Comment by faustbrian** [comment]
Will take a look on monday.

**Comment by dafty** [comment]
Looks like pg_dump already uses gunzip as part of it's default settings, so impact is minimal (20mb).
